In [39]:
import os
import json
import tempfile
from dotenv import load_dotenv
import pandas as pd 
import gradio as gr 
from openai import OpenAI
from anthropic import Anthropic

In [41]:
load_dotenv(override=True)

openai_api_key = os.getenv('OPENAI_API_KEY')
anthropic_api_key = os.getenv('ANTHROPIC_API_KEY')

if openai_api_key:
    print(f"OpenAI API Key exists and begins {openai_api_key[:8]}")
else:
    print("OpenAI API Key not set")
    
if anthropic_api_key:
    print(f"Anthropic API Key exists and begins {anthropic_api_key[:7]}")
else:
    print("Anthropic API Key not set (and this is optional)")

openai = OpenAI(api_key=openai_api_key)
anthropic = Anthropic(api_key=anthropic_api_key)

OpenAI API Key exists and begins sk-proj-
Anthropic API Key exists and begins sk-ant-

In [42]:
OPENAI_MODEL = "gpt-5.4-mini"
CLAUDE_MODEL = "claude-haiku-4-5"

## Schema Function

In [44]:

def create_schema(description):

    system_prompt = "You design clean schemas for synthetic datasets."

    user_prompt = f"""
you are a data schema designer.
The user wants to generate this synthentic dataset: 
{description}
Design a useful schema for this dataset.
Return ONLY valid JSON in this format:
{{
    "dataset_name:" "string",
    "description": "string",
    "columns": [
        {{
            "name": "column_name",
            "type": "string|integer|number|boolean",
            "description": "what this field represents"
        }}
    ]
}}

Rules:

- Create between 5 and 10 columns.
- Use realistic columns.
- Include a target variable if appropriate.
- Use only these types:
  string
  integer
  number
  boolean
- Do not create unnecessary columns.
"""
    messages = [{"role": "system", "content": system_prompt},{"role": "user", "content": user_prompt}]
    response = openai.chat.completions.create(model = OPENAI_MODEL, messages=messages, response_format={"type": "json_object"}, temperature=0.4)
  
    return json.loads(response.choices[0].message.content)

In [45]:
description = """
Create a synthetic dataset for predicting telecom customer churn.
Include customer demographics, billing information and usage behaviour.
"""

schema = create_schema(description)

print(json.dumps(schema, indent = 2))

{
  "dataset_name": "telecom_customer_churn",
  "description": "Synthetic dataset for predicting whether a telecom customer will churn, including customer demographics, billing information, and usage behavior.",
  "columns": [
    {
      "name": "customer_id",
      "type": "string",
      "description": "Unique identifier for each customer"
    },
    {
      "name": "age",
      "type": "integer",
      "description": "Customer age in years"
    },
    {
      "name": "tenure_months",
      "type": "integer",
      "description": "Number of months the customer has been with the telecom provider"
    },
    {
      "name": "monthly_charge",
      "type": "number",
      "description": "Current monthly billing amount for the customer"
    },
    {
      "name": "total_data_usage_gb",
      "type": "number",
      "description": "Total mobile or internet data used by the customer in gigabytes"
    },
    {
      "name": "support_calls_last_3_months",
      "type": "integer",
      "description": "Number of customer support calls made in the last three months"
    },
    {
      "name": "contract_type",
      "type": "string",
      "description": "Type of customer contract, such as month-to-month or annual"
    },
    {
      "name": "churned",
      "type": "boolean",
      "description": "Whether the customer canceled service within the prediction period"
    }
  ]
}

## Generating Data set with OpenAI function

In [ ]:
def generate_with_openai(schema,num_rows):

    schema_text = json.dumps(schema, indent = 2)

    system_prompt = "You generate realistic synthetic tabular data."
    user_prompt = f"""
Generate {num_rows=} realistic synthetic records.
Dataset schema: {schema_text}
Requirements: 
- Return ONLY valid JSON.
- Return an object with a "rows" key. 
- "rows" must contain exactly {num_rows} records.
- Follow the column nammes and data types.
- Values should be realistic.
- Do not use null values.
- Avoid duplicate records.
- Create realistic relationships between fields.
- Make the records diverse. 
Format:
{{
    "rows": [
    {{
        "column_name": "value"
    }}
    ]
}}
"""
    messages = [{"role": "system", "content": system_prompt},{"role": "user", "content": user_prompt}]
    response = openai.chat.completions.create(model = OPENAI_MODEL, messages = messages,response_format={"type": "json_object"}, temperature= 0.8)
    
    data = json.loads(response.choices[0].message.content)

    return data["rows"]

## Generating Data set with Claude function

In [107]:
from pandas.core.arrays import categorical


def generate_with_claude(schema, num_rows):

    schema_text = json.dumps(schema, indent = 2)

    system_prompt = "You are a synthetic data generation specialist."

    user_prompt = f"""
Generate {num_rows} realistic records using this schema:
{schema_text}
Return ONLY valid JSON:
{{
    "rows": [
    {{
        "column_name": "value"
    }}
    ]
}}
Requirments:
- Generate exactly {num_rows} records.
- Follow the schema exactly.
- Avoid duplicates.
- Make the records diverse. 
- Create realistic relationships between variables. 
- Do not use Markdown code fences.
- Do not generate null values. 
- Vary categorical and numerical values naturally. 
- Avoid making every record look similar. 
"""

    response = anthropic.messages.create(model = CLAUDE_MODEL, max_tokens = 12000, temperature=0.8,system= system_prompt, messages= [{"role": "user", "content": user_prompt}])
    
    text = response.content[0].text.strip()

    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[len("json"):]
        text = text.strip()

    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"Claude did not return valid JSON.\n"
            f"stop_reason={response.stop_reason}\n"
            f"First 300 chars: {text[:300]}"
        ) from e


    return data["rows"]

## Testing both generators

In [70]:
openai_data = generate_with_openai(schema,10)
claude_data = generate_with_claude(schema,10)

print("OpenAI records:" , len(openai_data))
print("Claude records:", len(claude_data))

GPT
{"rows":[{"customer_id":"CUST-1001","age":24,"tenure_months":4,"monthly_charge":79.99,"total_data_usage_gb":68.4,"support_calls_last_3_months":3,"contract_type":"month-to-month","churned":true},{"customer_id":"CUST-1002","age":41,"tenure_months":36,"monthly_charge":54.5,"total_data_usage_gb":124.7,"support_calls_last_3_months":0,"contract_type":"annual","churned":false},{"customer_id":"CUST-1003","age":58,"tenure_months":8,"monthly_charge":92.3,"total_data_usage_gb":42.1,"support_calls_last_3_months":4,"contract_type":"month-to-month","churned":true},{"customer_id":"CUST-1004","age":33,"tenure_months":18,"monthly_charge":68.0,"total_data_usage_gb":210.5,"support_calls_last_3_months":1,"contract_type":"two-year","churned":false},{"customer_id":"CUST-1005","age":29,"tenure_months":12,"monthly_charge":45.99,"total_data_usage_gb":95.2,"support_calls_last_3_months":2,"contract_type":"annual","churned":false},{"customer_id":"CUST-1006","age":67,"tenure_months":2,"monthly_charge":88.75,"total_data_usage_gb":18.6,"support_calls_last_3_months":5,"contract_type":"month-to-month","churned":true},{"customer_id":"CUST-1007","age":46,"tenure_months":54,"monthly_charge":72.4,"total_data_usage_gb":340.8,"support_calls_last_3_months":1,"contract_type":"two-year","churned":false},{"customer_id":"CUST-1008","age":22,"tenure_months":6,"monthly_charge":39.95,"total_data_usage_gb":56.9,"support_calls_last_3_months":1,"contract_type":"month-to-month","churned":false},{"customer_id":"CUST-1009","age":52,"tenure_months":27,"monthly_charge":84.2,"total_data_usage_gb":154.3,"support_calls_last_3_months":2,"contract_type":"annual","churned":false},{"customer_id":"CUST-1010","age":38,"tenure_months":3,"monthly_charge":96.5,"total_data_usage_gb":12.4,"support_calls_last_3_months":6,"contract_type":"month-to-month","churned":true}]}
Claude
{
    "rows": [
        {
            "customer_id": "CUST001847",
            "age": 34,
            "tenure_months": 24,
            "monthly_charge": 65.99,
            "total_data_usage_gb": 156.3,
            "support_calls_last_3_months": 2,
            "contract_type": "annual",
            "churned": false
        },
        {
            "customer_id": "CUST002156",
            "age": 67,
            "tenure_months": 8,
            "monthly_charge": 45.50,
            "total_data_usage_gb": 12.7,
            "support_calls_last_3_months": 5,
            "contract_type": "month-to-month",
            "churned": true
        },
        {
            "customer_id": "CUST003421",
            "age": 28,
            "tenure_months": 42,
            "monthly_charge": 89.99,
            "total_data_usage_gb": 287.5,
            "support_calls_last_3_months": 1,
            "contract_type": "annual",
            "churned": false
        },
        {
            "customer_id": "CUST004789",
            "age": 55,
            "tenure_months": 15,
            "monthly_charge": 72.25,
            "total_data_usage_gb": 98.2,
            "support_calls_last_3_months": 4,
            "contract_type": "month-to-month",
            "churned": true
        },
        {
            "customer_id": "CUST005634",
            "age": 41,
            "tenure_months": 36,
            "monthly_charge": 55.75,
            "total_data_usage_gb": 134.8,
            "support_calls_last_3_months": 0,
            "contract_type": "annual",
            "churned": false
        },
        {
            "customer_id": "CUST006912",
            "age": 23,
            "tenure_months": 6,
            "monthly_charge": 95.50,
            "total_data_usage_gb": 412.1,
            "support_calls_last_3_months": 3,
            "contract_type": "month-to-month",
            "churned": true
        },
        {
            "customer_id": "CUST007245",
            "age": 52,
            "tenure_months": 60,
            "monthly_charge": 48.99,
            "total_data_usage_gb": 45.3,
            "support_calls_last_3_months": 1,
            "contract_type": "annual",
            "churned": false
        },
        {
            "customer_id": "CUST008567",
            "age": 38,
            "tenure_months": 11,
            "monthly_charge": 82.40,
            "total_data_usage_gb": 203.7,
            "support_calls_last_3_months": 6,
            "contract_type": "month-to-month",
            "churned": true
        },
        {
            "customer_id": "CUST009103",
            "age": 45,
            "tenure_months": 48,
            "monthly_charge": 61.50,
            "total_data_usage_gb": 167.4,
            "support_calls_last_3_months": 2,
            "contract_type": "annual",
            "churned": false
        },
        {
            "customer_id": "CUST010456",
            "age": 31,
            "tenure_months": 9,
            "monthly_charge": 99.99,
            "total_data_usage_gb": 521.2,
            "support_calls_last_3_months": 7,
            "contract_type": "month-to-month",
            "churned": true
        }
    ]
}
OpenAI records: 10
Claude records: 10

In [71]:
openai_data[:2]

[{'customer_id': 'CUST-1001',
  'age': 24,
  'tenure_months': 4,
  'monthly_charge': 79.99,
  'total_data_usage_gb': 68.4,
  'support_calls_last_3_months': 3,
  'contract_type': 'month-to-month',
  'churned': True},
 {'customer_id': 'CUST-1002',
  'age': 41,
  'tenure_months': 36,
  'monthly_charge': 54.5,
  'total_data_usage_gb': 124.7,
  'support_calls_last_3_months': 0,
  'contract_type': 'annual',
  'churned': False}]

In [72]:
claude_data[:2]

[{'customer_id': 'CUST001847',
  'age': 34,
  'tenure_months': 24,
  'monthly_charge': 65.99,
  'total_data_usage_gb': 156.3,
  'support_calls_last_3_months': 2,
  'contract_type': 'annual',
  'churned': False},
 {'customer_id': 'CUST002156',
  'age': 67,
  'tenure_months': 8,
  'monthly_charge': 45.5,
  'total_data_usage_gb': 12.7,
  'support_calls_last_3_months': 5,
  'contract_type': 'month-to-month',
  'churned': True}]

## Combine into Pandas

In [73]:
def combine_data(openai_data, claude_data, schema):
    all_rows = openai_data + claude_data

    dataframe = pd.DataFrame(all_rows)

    column_order = [
        column["name"]
        for column in schema["columns"]
    ]
    existing_columns = [
        column
        for column in column_order
        if column in dataframe.columns
    ]

    dataframe = dataframe[existing_columns]

    return dataframe

In [74]:
df = combine_data(openai_data,claude_data,schema)

df

,customer_id,age,tenure_months,monthly_charge,total_data_usage_gb,support_calls_last_3_months,contract_type,churned
0,CUST-1001,24,4,79.99,68.4,3,month-to-month,True
1,CUST-1002,41,36,54.50,124.7,0,annual,False
2,CUST-1003,58,8,92.30,42.1,4,month-to-month,True
3,CUST-1004,33,18,68.00,210.5,1,two-year,False
4,CUST-1005,29,12,45.99,95.2,2,annual,False
5,CUST-1006,67,2,88.75,18.6,5,month-to-month,True
6,CUST-1007,46,54,72.40,340.8,1,two-year,False
7,CUST-1008,22,6,39.95,56.9,1,month-to-month,False
8,CUST-1009,52,27,84.20,154.3,2,annual,False
9,CUST-1010,38,3,96.50,12.4,6,month-to-month,True
10,CUST001847,34,24,65.99,156.3,2,annual,False
11,CUST002156,67,8,45.50,12.7,5,month-to-month,True
12,CUST003421,28,42,89.99,287.5,1,annual,False
13,CUST004789,55,15,72.25,98.2,4,month-to-month,True
14,CUST005634,41,36,55.75,134.8,0,annual,False
15,CUST006912,23,6,95.50,412.1,3,month-to-month,True
16,CUST007245,52,60,48.99,45.3,1,annual,False
17,CUST008567,38,11,82.40,203.7,6,month-to-month,True
18,CUST009103,45,48,61.50,167.4,2,annual,False
19,CUST010456,31,9,99.99,521.2,7,month-to-month,True

## Validation

In [ ]:
def validate_dataframe (dataframe, schema):
    expected_columns = [
        column['name']
        for column in schema["columns"]
    ]

    missing_columns = [
        column
        for column in expected_columns
        if column not in dataframe.columns
    ]

    duplicate_rows = int(
        dataframe.duplicated().sum()
    )

    missing_values = int(
        dataframe.isnull().sum().sum()
    )

    return {
        "rows": len(dataframe),
        "columns": len(dataframe.columns),
        "missing_columns": missing_columns,
        "duplicate_rows": duplicate_rows,
        "missing_values": missing_values
    }

In [76]:
validation = validate_dataframe(df,schema)

validation

{'rows': 20,
 'columns': 8,
 'missing_columns': [],
 'duplicate_rows': 0,
 'missing_values': 0}

## Critic Agent Function

In [93]:
def critique_dataset(schema, dataframe):

    sample = dataframe.head(20).to_dict(
        orient= "records"
    )

    system_prompt = "You are a data quality critic."

    user_prompt = f"""
We generated a synthetic dataset using this schema:
{json.dumps(schema, indent=2)}
Here is the sample of the generated data:
{json.dumps(sample, indent=2)}
Return ONLY valid JSON:

{{
    "quality_score": 0,
    "issues": [],
    "strengths": [],
    "recommendations": ""
}}

{{
    "quality_score": 85,
    "issues": [
        "Some customers have unusually high data usage for their contract type."
    ],
    "strengths": [
        "No missing values were observed.",
        "The categorical values are consistent.",
        "The dataset contains reasonable variation."
    ],
    "recommendations": "Consider increasing variation in customer tenure and monthly charges."
}}


Requirements:

- Do not use Markdown code fences.
- Do not include any explanation before or after the JSON.
- Quality score must be between 0 and 100.

Check for:

- incorrect data types
- unrealistic values
- duplicate-looking records
- inconsistent categories
- suspicious relationships 
- lack of diversity 
- missing values
- obvious generation artifacts

Give a quality score from 0 to 100
"""
    messages = [{"role":"user", "content":user_prompt}]
    response = anthropic.messages.create(model = CLAUDE_MODEL, max_tokens=2000, system= system_prompt,messages=messages)

    text = response.content[0].text.strip()
    if text.startswith("```"):
       text = text.strip("`").removeprefix("json").strip()
    try:
       return json.loads(text)
    except json.JSONDecodeError as e:
       raise ValueError(f"Model did not return valid JSON: {text[:200]}") from e

In [ ]:
critique = critique_dataset(schema,df)

In [95]:
critique

{'quality_score': 72,
 'issues': ["Inconsistent customer_id formatting: mix of 'CUST-####' and 'CUST######' patterns suggests incomplete standardization",
  'Suspicious correlation patterns: churned customers consistently have low tenure (2-15 months) and high support calls (3-7), while non-churned have high tenure and low support calls - too perfectly separated',
  'Unrealistic data usage variance: same age/tenure cohorts show extreme variation (e.g., CUST010456 with 521.2 GB vs CUST008567 with 203.7 GB, both similar profiles)',
  'Potential generation artifact: churned=true strongly correlates with month-to-month contracts (10/10 churned samples) and support_calls >= 3, suggesting rule-based generation rather than realistic patterns',
  'Missing realistic edge cases: no customers with very high tenure and churn, or low support calls with churn'],
 'strengths': ['No missing values across all records',
  'All data types match schema correctly',
  'Age range (22-67) is realistic for telecom customers',
  'Tenure values are plausible (2-60 months)',
  'Monthly charges show reasonable range ($39.95-$99.99)',
  'Contract types are valid and present variety'],
 'recommendations': "Reduce the deterministic relationship between contract_type and churn outcome. Introduce more realistic variance in support calls and data usage independent of tenure. Standardize customer_id format consistently. Add more edge cases: long-term customers who churn, high data users with low bills, and customers with high support needs who don't churn. Reduce the perfect correlation between churn and multiple features to increase realism."}

## Complete Pipeline

In [96]:
def generate_dataset(description, num_rows = 50):
    
    print("Creating schema...")
    schema = create_schema(description)
    print(f"Created {len(schema['columns'])} columns")

    openai_rows = num_rows // 2 
    claude_rows = num_rows - openai_rows 

    print(f"OpenAI generating {openai_rows} records...")
    openai_data = generate_with_openai(schema,openai_rows)

    print(f"Claude generating {claude_rows} records...")
    claude_data = generate_with_claude(schema,claude_rows)

    print("Combining datasets...")
    dataframe = combine_data(openai_data,claude_data,schema)

    print("Running validation...")
    validation = validate_dataframe(dataframe,schema)

    print("Critic reviewing dataset...")
    critique = critique_dataset(schema, dataframe)

    print("Generation complete!")

    return{
        "schema": schema,
        "dataframe": dataframe,
        "validation": validation,
        "critique": critique
    }

## Testing the entire pipeline

In [97]:
description = """ 
Create a synthetic customer churn dataset
for a telecommunications company.

Include customer demographics, billing information,
service usage and whether the customer churned.
"""

result = generate_dataset(description, num_rows=50)

Creating schema...
Created 8 columns
OpenAI generating 25 records...
GPT
{"rows":[{"customer_age":24,"gender":"Female","tenure_months":3,"monthly_charges":68.4,"total_data_usage_gb":142.7,"num_support_calls":2,"contract_type":"Month-to-month","churned":true},{"customer_age":57,"gender":"Male","tenure_months":48,"monthly_charges":84.9,"total_data_usage_gb":310.2,"num_support_calls":1,"contract_type":"Two-year","churned":false},{"customer_age":36,"gender":"Female","tenure_months":15,"monthly_charges":59.3,"total_data_usage_gb":96.8,"num_support_calls":0,"contract_type":"One-year","churned":false},{"customer_age":29,"gender":"Male","tenure_months":6,"monthly_charges":92.1,"total_data_usage_gb":420.5,"num_support_calls":4,"contract_type":"Month-to-month","churned":true},{"customer_age":44,"gender":"Female","tenure_months":22,"monthly_charges":73.8,"total_data_usage_gb":188.4,"num_support_calls":1,"contract_type":"One-year","churned":false},{"customer_age":63,"gender":"Male","tenure_months":72,"monthly_charges":101.6,"total_data_usage_gb":512.9,"num_support_calls":0,"contract_type":"Two-year","churned":false},{"customer_age":31,"gender":"Female","tenure_months":9,"monthly_charges":64.7,"total_data_usage_gb":121.3,"num_support_calls":3,"contract_type":"Month-to-month","churned":true},{"customer_age":52,"gender":"Male","tenure_months":36,"monthly_charges":88.2,"total_data_usage_gb":276.1,"num_support_calls":1,"contract_type":"One-year","churned":false},{"customer_age":27,"gender":"Female","tenure_months":12,"monthly_charges":54.6,"total_data_usage_gb":84.5,"num_support_calls":0,"contract_type":"One-year","churned":false},{"customer_age":40,"gender":"Male","tenure_months":5,"monthly_charges":79.5,"total_data_usage_gb":233.8,"num_support_calls":5,"contract_type":"Month-to-month","churned":true},{"customer_age":48,"gender":"Female","tenure_months":60,"monthly_charges":112.3,"total_data_usage_gb":610.4,"num_support_calls":2,"contract_type":"Two-year","churned":false},{"customer_age":22,"gender":"Male","tenure_months":2,"monthly_charges":49.9,"total_data_usage_gb":38.6,"num_support_calls":1,"contract_type":"Month-to-month","churned":true},{"customer_age":34,"gender":"Female","tenure_months":18,"monthly_charges":71.2,"total_data_usage_gb":159.7,"num_support_calls":0,"contract_type":"One-year","churned":false},{"customer_age":60,"gender":"Male","tenure_months":84,"monthly_charges":97.4,"total_data_usage_gb":455.1,"num_support_calls":1,"contract_type":"Two-year","churned":false},{"customer_age":39,"gender":"Female","tenure_months":7,"monthly_charges":86.8,"total_data_usage_gb":298.9,"num_support_calls":4,"contract_type":"Month-to-month","churned":true},{"customer_age":46,"gender":"Male","tenure_months":27,"monthly_charges":76.5,"total_data_usage_gb":210.6,"num_support_calls":2,"contract_type":"One-year","churned":false},{"customer_age":28,"gender":"Female","tenure_months":14,"monthly_charges":61.8,"total_data_usage_gb":130.2,"num_support_calls":1,"contract_type":"Month-to-month","churned":false},{"customer_age":55,"gender":"Male","tenure_months":41,"monthly_charges":95.7,"total_data_usage_gb":344.8,"num_support_calls":0,"contract_type":"Two-year","churned":false},{"customer_age":33,"gender":"Female","tenure_months":4,"monthly_charges":74.1,"total_data_usage_gb":176.9,"num_support_calls":3,"contract_type":"Month-to-month","churned":true},{"customer_age":67,"gender":"Male","tenure_months":96,"monthly_charges":89.6,"total_data_usage_gb":389.3,"num_support_calls":1,"contract_type":"Two-year","churned":false},{"customer_age":26,"gender":"Female","tenure_months":11,"monthly_charges":58.2,"total_data_usage_gb":102.4,"num_support_calls":0,"contract_type":"One-year","churned":false},{"customer_age":41,"gender":"Male","tenure_months":30,"monthly_charges":82.7,"total_data_usage_gb":245.7,"num_support_calls":2,"contract_type":"One-year","churned":false},{"customer_age":38,"gender":"Female","tenure_months":8,"monthly_charges":90.4,"total_data_usage_gb":367.2,"num_support_calls":5,"contract_type":"Month-to-month","churned":true},{"customer_age":50,"gender":"Male","tenure_months":54,"monthly_charges":105.8,"total_data_usage_gb":498.6,"num_support_calls":1,"contract_type":"Two-year","churned":false},{"customer_age":30,"gender":"Female","tenure_months":20,"monthly_charges":66.9,"total_data_usage_gb":148.5,"num_support_calls":0,"contract_type":"One-year","churned":false}]}
Claude generating 25 records...
Claude
{
  "rows": [
    {
      "customer_age": 28,
      "gender": "Male",
      "tenure_months": 6,
      "monthly_charges": 65.50,
      "total_data_usage_gb": 45.2,
      "num_support_calls": 3,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 45,
      "gender": "Female",
      "tenure_months": 48,
      "monthly_charges": 85.99,
      "total_data_usage_gb": 22.5,
      "num_support_calls": 1,
      "contract_type": "annual",
      "churned": false
    },
    {
      "customer_age": 35,
      "gender": "Male",
      "tenure_months": 24,
      "monthly_charges": 72.40,
      "total_data_usage_gb": 58.9,
      "num_support_calls": 2,
      "contract_type": "two-year",
      "churned": false
    },
    {
      "customer_age": 52,
      "gender": "Female",
      "tenure_months": 72,
      "monthly_charges": 95.25,
      "total_data_usage_gb": 12.3,
      "num_support_calls": 0,
      "contract_type": "annual",
      "churned": false
    },
    {
      "customer_age": 31,
      "gender": "Male",
      "tenure_months": 3,
      "monthly_charges": 55.00,
      "total_data_usage_gb": 78.6,
      "num_support_calls": 5,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 42,
      "gender": "Female",
      "tenure_months": 36,
      "monthly_charges": 89.75,
      "total_data_usage_gb": 35.4,
      "num_support_calls": 1,
      "contract_type": "two-year",
      "churned": false
    },
    {
      "customer_age": 26,
      "gender": "Male",
      "tenure_months": 12,
      "monthly_charges": 49.99,
      "total_data_usage_gb": 92.1,
      "num_support_calls": 4,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 58,
      "gender": "Male",
      "tenure_months": 84,
      "monthly_charges": 105.50,
      "total_data_usage_gb": 8.7,
      "num_support_calls": 0,
      "contract_type": "annual",
      "churned": false
    },
    {
      "customer_age": 39,
      "gender": "Female",
      "tenure_months": 18,
      "monthly_charges": 79.99,
      "total_data_usage_gb": 41.2,
      "num_support_calls": 2,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 47,
      "gender": "Male",
      "tenure_months": 60,
      "monthly_charges": 98.40,
      "total_data_usage_gb": 19.5,
      "num_support_calls": 1,
      "contract_type": "two-year",
      "churned": false
    },
    {
      "customer_age": 33,
      "gender": "Female",
      "tenure_months": 9,
      "monthly_charges": 62.75,
      "total_data_usage_gb": 67.3,
      "num_support_calls": 3,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 55,
      "gender": "Female",
      "tenure_months": 96,
      "monthly_charges": 110.99,
      "total_data_usage_gb": 5.2,
      "num_support_calls": 0,
      "contract_type": "annual",
      "churned": false
    },
    {
      "customer_age": 29,
      "gender": "Male",
      "tenure_months": 42,
      "monthly_charges": 84.50,
      "total_data_usage_gb": 51.8,
      "num_support_calls": 2,
      "contract_type": "two-year",
      "churned": false
    },
    {
      "customer_age": 44,
      "gender": "Male",
      "tenure_months": 15,
      "monthly_charges": 68.99,
      "total_data_usage_gb": 73.6,
      "num_support_calls": 4,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 38,
      "gender": "Female",
      "tenure_months": 54,
      "monthly_charges": 92.25,
      "total_data_usage_gb": 28.4,
      "num_support_calls": 1,
      "contract_type": "annual",
      "churned": false
    },
    {
      "customer_age": 27,
      "gender": "Female",
      "tenure_months": 5,
      "monthly_charges": 58.50,
      "total_data_usage_gb": 85.2,
      "num_support_calls": 6,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 50,
      "gender": "Male",
      "tenure_months": 66,
      "monthly_charges": 101.75,
      "total_data_usage_gb": 15.9,
      "num_support_calls": 0,
      "contract_type": "two-year",
      "churned": false
    },
    {
      "customer_age": 36,
      "gender": "Female",
      "tenure_months": 30,
      "monthly_charges": 76.40,
      "total_data_usage_gb": 46.7,
      "num_support_calls": 2,
      "contract_type": "two-year",
      "churned": false
    },
    {
      "customer_age": 41,
      "gender": "Male",
      "tenure_months": 21,
      "monthly_charges": 71.99,
      "total_data_usage_gb": 62.3,
      "num_support_calls": 3,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 53,
      "gender": "Female",
      "tenure_months": 78,
      "monthly_charges": 107.50,
      "total_data_usage_gb": 11.4,
      "num_support_calls": 0,
      "contract_type": "annual",
      "churned": false
    },
    {
      "customer_age": 32,
      "gender": "Male",
      "tenure_months": 7,
      "monthly_charges": 61.25,
      "total_data_usage_gb": 80.5,
      "num_support_calls": 5,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 46,
      "gender": "Female",
      "tenure_months": 48,
      "monthly_charges": 94.99,
      "total_data_usage_gb": 24.6,
      "num_support_calls": 1,
      "contract_type": "annual",
      "churned": false
    },
    {
      "customer_age": 34,
      "gender": "Male",
      "tenure_months": 27,
      "monthly_charges": 81.50,
      "total_data_usage_gb": 55.2,
      "num_support_calls": 2,
      "contract_type": "two-year",
      "churned": false
    },
    {
      "customer_age": 40,
      "gender": "Female",
      "tenure_months": 14,
      "monthly_charges": 67.75,
      "total_data_usage_gb": 70.1,
      "num_support_calls": 4,
      "contract_type": "month-to-month",
      "churned": true
    },
    {
      "customer_age": 51,
      "gender": "Male",
      "tenure_months": 72,
      "monthly_charges": 103.25,
      "total_data_usage_gb": 13.8,
      "num_support_calls": 0,
      "contract_type": "annual",
      "churned": false
    }
  ]
}
Combining datasets...
Running validation...
Critic reviewing dataset...
Generation complete!

In [98]:
result["dataframe"]

,customer_age,gender,tenure_months,monthly_charges,total_data_usage_gb,num_support_calls,contract_type,churned
0,24,Female,3,68.40,142.7,2,Month-to-month,True
1,57,Male,48,84.90,310.2,1,Two-year,False
2,36,Female,15,59.30,96.8,0,One-year,False
3,29,Male,6,92.10,420.5,4,Month-to-month,True
4,44,Female,22,73.80,188.4,1,One-year,False
5,63,Male,72,101.60,512.9,0,Two-year,False
6,31,Female,9,64.70,121.3,3,Month-to-month,True
7,52,Male,36,88.20,276.1,1,One-year,False
8,27,Female,12,54.60,84.5,0,One-year,False
9,40,Male,5,79.50,233.8,5,Month-to-month,True
10,48,Female,60,112.30,610.4,2,Two-year,False
11,22,Male,2,49.90,38.6,1,Month-to-month,True
12,34,Female,18,71.20,159.7,0,One-year,False
13,60,Male,84,97.40,455.1,1,Two-year,False
14,39,Female,7,86.80,298.9,4,Month-to-month,True
15,46,Male,27,76.50,210.6,2,One-year,False
16,28,Female,14,61.80,130.2,1,Month-to-month,False
17,55,Male,41,95.70,344.8,0,Two-year,False
18,33,Female,4,74.10,176.9,3,Month-to-month,True
19,67,Male,96,89.60,389.3,1,Two-year,False
20,26,Female,11,58.20,102.4,0,One-year,False
21,41,Male,30,82.70,245.7,2,One-year,False
22,38,Female,8,90.40,367.2,5,Month-to-month,True
23,50,Male,54,105.80,498.6,1,Two-year,False
24,30,Female,20,66.90,148.5,0,One-year,False
25,28,Male,6,65.50,45.2,3,month-to-month,True
26,45,Female,48,85.99,22.5,1,annual,False
27,35,Male,24,72.40,58.9,2,two-year,False
28,52,Female,72,95.25,12.3,0,annual,False
29,31,Male,3,55.00,78.6,5,month-to-month,True
30,42,Female,36,89.75,35.4,1,two-year,False
31,26,Male,12,49.99,92.1,4,month-to-month,True
32,58,Male,84,105.50,8.7,0,annual,False
33,39,Female,18,79.99,41.2,2,month-to-month,True
34,47,Male,60,98.40,19.5,1,two-year,False
35,33,Female,9,62.75,67.3,3,month-to-month,True
36,55,Female,96,110.99,5.2,0,annual,False
37,29,Male,42,84.50,51.8,2,two-year,False
38,44,Male,15,68.99,73.6,4,month-to-month,True
39,38,Female,54,92.25,28.4,1,annual,False
40,27,Female,5,58.50,85.2,6,month-to-month,True
41,50,Male,66,101.75,15.9,0,two-year,False
42,36,Female,30,76.40,46.7,2,two-year,False
43,41,Male,21,71.99,62.3,3,month-to-month,True
44,53,Female,78,107.50,11.4,0,annual,False
45,32,Male,7,61.25,80.5,5,month-to-month,True
46,46,Female,48,94.99,24.6,1,annual,False
47,34,Male,27,81.50,55.2,2,two-year,False
48,40,Female,14,67.75,70.1,4,month-to-month,True
49,51,Male,72,103.25,13.8,0,annual,False

In [99]:
print(json.dumps(result["schema"], indent = 2))

{
  "dataset_name": "telecom_customer_churn",
  "description": "Synthetic customer churn dataset for a telecommunications company, including customer demographics, billing information, service usage, and a churn target.",
  "columns": [
    {
      "name": "customer_age",
      "type": "integer",
      "description": "Age of the customer in years"
    },
    {
      "name": "gender",
      "type": "string",
      "description": "Customer gender"
    },
    {
      "name": "tenure_months",
      "type": "integer",
      "description": "Number of months the customer has been with the company"
    },
    {
      "name": "monthly_charges",
      "type": "number",
      "description": "Total monthly billing amount for the customer"
    },
    {
      "name": "total_data_usage_gb",
      "type": "number",
      "description": "Total monthly data usage in gigabytes"
    },
    {
      "name": "num_support_calls",
      "type": "integer",
      "description": "Number of customer support calls made in the billing period"
    },
    {
      "name": "contract_type",
      "type": "string",
      "description": "Type of customer contract, such as month-to-month or annual"
    },
    {
      "name": "churned",
      "type": "boolean",
      "description": "Whether the customer churned"
    }
  ]
}

In [100]:
result["validation"]

{'rows': 50,
 'columns': 8,
 'missing_columns': [],
 'duplicate_rows': 0,
 'missing_values': 0}

In [ ]:
print(json.dumps(result["critique"], indent = 2))

{
  "quality_score": 72,
  "issues": [
    "Strong artificial correlation between tenure_months and monthly_charges - longer tenure consistently results in higher charges, which is unrealistic for telecom billing",
    "Perfect correlation between num_support_calls and churned status - customers with 3+ support calls always churn, suggesting oversimplified synthetic generation",
    "Data usage values appear suspiciously high relative to typical mobile/telecom usage patterns (up to 610GB monthly is unrealistic for individual consumers)",
    "Monthly charges show artificial banding around specific price points ($49.9-$112.3) with limited realistic variation",
    "Gender distribution appears perfectly balanced (10 Female, 10 Male in sample) suggesting synthetic uniformity rather than real-world variation",
    "Churn rate of 40% in sample (8/20) is notably high and may not reflect realistic telecom industry rates"
  ],
  "strengths": [
    "No missing values present in any field",
    "Data types are correctly specified and consistently applied",
    "Customer age range (22-67) is realistic and diverse",
    "Tenure values span reasonable range from 2 to 96 months",
    "No obviously duplicate records detected",
    "Contract type values are consistent and realistic"
  ],
  "recommendations": "Reduce artificial correlations between features - particularly decouple tenure from monthly charges and support calls from churn. Implement more realistic data usage patterns (50-200GB range). Add variance to price points and avoid perfect binary relationships. Consider decreasing overall churn rate to 5-15% range. Add additional demographic variables to increase realism."
}

## Gradio

In [113]:
def gradio_generate(description, num_rows):

    result = generate_dataset(description, int(num_rows))

    schema = result["schema"]
    dataframe = result["dataframe"]
    validation = result["validation"]
    critique = result ["critique"]

    quality_report = f"""
## Dataset Quality

**AI Quality Score:** {critique["quality_score"]}/100

**Rows:** {validation["rows"]}

**Columns:** {validation["columns"]}

**Missing Values:** {validation["missing_values"]}
    
**Duplicate Rows:** {validation["duplicate_rows"]}

### Strengths

{chr(10).join("- " + x for x in critique["strengths"])}

### Issues

{chr(10).join("- " + x for x in critique["issues"])}

### Recommendation

{critique["recommendations"]}
"""

    schema_text = json.dumps(schema, indent=2)
    return dataframe, schema_text, quality_report

In [114]:
with gr.Blocks(title = "Synthetic Data Foundry") as generator:

    gr.Markdown(
        """
# Synthetic Data Foundry 

### Multi-Agent Synthetic Dataset Generator

Generate synthetic datasets using OpenAI and Claude.
"""
    )

    with gr.Tab("Generate"):
        description = gr.Textbox(
            label = "Dataset Description",
            placeholder = "Example: Generate a telecom customer churn dataset...",
            lines = 5
        )
        num_rows = gr.Slider(minimum=10, maximum=100, value=50, step=10, label="Number of Records")
        generate_button = gr.Button("Generate Dataset", variant = "primary")
    
    with gr.Tab("Dataset"):
        dataframe_output = gr.Dataframe(label="Generate Dataset", interactive=False)

    with gr.Tab("Schema"):
        schema_output = gr.Code(label="Generated Schema", language="json")

    with gr.Tab("Quality Report"):
        quality_output = gr.Markdown("Generate a dataset to see the quality report.")

    generate_button.click(
        fn = gradio_generate,
        inputs = [description, num_rows],
        outputs = [dataframe_output, schema_output, quality_output]
    )

In [116]:
generator.launch(inbrowser= True )

Rerunning server... use `close()` to stop if you need to change `launch()` parameters.
----
* To create a public link, set `share=True` in `launch()`.

Creating schema...
Created 8 columns
OpenAI generating 25 records...
GPT
{"rows":[{"age":78,"sex":"Female","systolic_blood_pressure":156.4,"heart_rate":92,"chronic_condition_count":5,"medication_count":11,"previous_hospital_stay_length_days":9,"readmitted_within_30_days":true},{"age":64,"sex":"Male","systolic_blood_pressure":148.2,"heart_rate":88,"chronic_condition_count":4,"medication_count":9,"previous_hospital_stay_length_days":7,"readmitted_within_30_days":true},{"age":49,"sex":"Female","systolic_blood_pressure":132.7,"heart_rate":79,"chronic_condition_count":2,"medication_count":5,"previous_hospital_stay_length_days":3,"readmitted_within_30_days":false},{"age":83,"sex":"Male","systolic_blood_pressure":164.9,"heart_rate":96,"chronic_condition_count":6,"medication_count":12,"previous_hospital_stay_length_days":12,"readmitted_within_30_days":true},{"age":57,"sex":"Female","systolic_blood_pressure":141.3,"heart_rate":84,"chronic_condition_count":3,"medication_count":7,"previous_hospital_stay_length_days":5,"readmitted_within_30_days":false},{"age":72,"sex":"Male","systolic_blood_pressure":151.8,"heart_rate":90,"chronic_condition_count":4,"medication_count":10,"previous_hospital_stay_length_days":8,"readmitted_within_30_days":true},{"age":36,"sex":"Female","systolic_blood_pressure":118.6,"heart_rate":72,"chronic_condition_count":1,"medication_count":2,"previous_hospital_stay_length_days":2,"readmitted_within_30_days":false},{"age":69,"sex":"Female","systolic_blood_pressure":145.5,"heart_rate":86,"chronic_condition_count":5,"medication_count":8,"previous_hospital_stay_length_days":6,"readmitted_within_30_days":true},{"age":44,"sex":"Male","systolic_blood_pressure":126.9,"heart_rate":76,"chronic_condition_count":2,"medication_count":4,"previous_hospital_stay_length_days":4,"readmitted_within_30_days":false},{"age":61,"sex":"Female","systolic_blood_pressure":138.4,"heart_rate":81,"chronic_condition_count":3,"medication_count":6,"previous_hospital_stay_length_days":5,"readmitted_within_30_days":false},{"age":85,"sex":"Female","systolic_blood_pressure":170.1,"heart_rate":99,"chronic_condition_count":7,"medication_count":13,"previous_hospital_stay_length_days":14,"readmitted_within_30_days":true},{"age":53,"sex":"Male","systolic_blood_pressure":133.8,"heart_rate":78,"chronic_condition_count":2,"medication_count":5,"previous_hospital_stay_length_days":3,"readmitted_within_30_days":false},{"age":76,"sex":"Female","systolic_blood_pressure":159.7,"heart_rate":94,"chronic_condition_count":5,"medication_count":11,"previous_hospital_stay_length_days":10,"readmitted_within_30_days":true},{"age":29,"sex":"Male","systolic_blood_pressure":121.2,"heart_rate":70,"chronic_condition_count":0,"medication_count":1,"previous_hospital_stay_length_days":1,"readmitted_within_30_days":false},{"age":67,"sex":"Male","systolic_blood_pressure":146.8,"heart_rate":87,"chronic_condition_count":4,"medication_count":8,"previous_hospital_stay_length_days":6,"readmitted_within_30_days":true},{"age":58,"sex":"Female","systolic_blood_pressure":140.9,"heart_rate":83,"chronic_condition_count":3,"medication_count":7,"previous_hospital_stay_length_days":4,"readmitted_within_30_days":false},{"age":81,"sex":"Male","systolic_blood_pressure":167.3,"heart_rate":97,"chronic_condition_count":6,"medication_count":12,"previous_hospital_stay_length_days":11,"readmitted_within_30_days":true},{"age":41,"sex":"Female","systolic_blood_pressure":128.5,"heart_rate":74,"chronic_condition_count":1,"medication_count":3,"previous_hospital_stay_length_days":2,"readmitted_within_30_days":false},{"age":74,"sex":"Female","systolic_blood_pressure":153.6,"heart_rate":91,"chronic_condition_count":4,"medication_count":9,"previous_hospital_stay_length_days":7,"readmitted_within_30_days":true},{"age":62,"sex":"Male","systolic_blood_pressure":144.1,"heart_rate":85,"chronic_condition_count":3,"medication_count":6,"previous_hospital_stay_length_days":5,"readmitted_within_30_days":false},{"age":47,"sex":"Male","systolic_blood_pressure":130.2,"heart_rate":77,"chronic_condition_count":2,"medication_count":4,"previous_hospital_stay_length_days":3,"readmitted_within_30_days":false},{"age":88,"sex":"Female","systolic_blood_pressure":172.4,"heart_rate":101,"chronic_condition_count":7,"medication_count":14,"previous_hospital_stay_length_days":15,"readmitted_within_30_days":true},{"age":55,"sex":"Male","systolic_blood_pressure":137.9,"heart_rate":82,"chronic_condition_count":3,"medication_count":6,"previous_hospital_stay_length_days":4,"readmitted_within_30_days":false},{"age":70,"sex":"Female","systolic_blood_pressure":149.6,"heart_rate":89,"chronic_condition_count":4,"medication_count":10,"previous_hospital_stay_length_days":8,"readmitted_within_30_days":true}]}
Claude generating 25 records...
Combining datasets...
Running validation...
Critic reviewing dataset...
Generation complete!